

image: docker:stable

services:
    - docker:dind


stages:
    - build
    - test
    - release
    - deploy

.dind: &dind
    before_script:
        - docker info
    services:
        - name: docker:dind
          command: ["--experimental"]

variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_TEST_IMAGE: registry.gitlab.com/doevelopper/doker-dev-stack/dev-image:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: registry.gitlab.com/doevelopper/doker-dev-stack/dev-image:latest

before_script:
    - echo "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com"

build:
    stage: build
    script:
        - echo "docker pull $CONTAINER_IMAGE:latest || true"
        - echo "docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest ."
        - echo "docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA"
        - echo "docker push $CONTAINER_IMAGE:latest"
          #        - docker login registry.gitlab.com
          #        - docker build -t registry.gitlab.com/doevelopper/doker-dev-stack .
          #        - docker push registry.gitlab.com/doevelopper/doker-dev-stack

test_build_image:
    image: docker:git
    tags:
        - doppler-docker
    services:
        - docker:dind
    script:
        - docker build .
    except:
        - tags

build_image:
    image: docker:git
    tags:
        - doppler-docker
    services:
        - docker:dind
    script:
        - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_TAG" .
        - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
        - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_TAG"
        - docker login -u "duniterteam" -p "$DUNITERTEAM_PASSWD"
        - docker tag "$CI_REGISTRY_IMAGE:$CI_BUILD_TAG" duniter/release-builder:"$CI_BUILD_TAG"
        - docker push duniter/release-builder:"$CI_BUILD_TAG"
    only:
        - tags

test1:
    stage: test
    script:
        - echo "docker pull $CONTAINER_TEST_IMAGE"
        - echo "docker run $CONTAINER_TEST_IMAGE /script/to/run/tests"

test2:
    stage: test
    script:
        - echo "docker pull $CONTAINER_TEST_IMAGE"
        - echo "docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test"

release-image:
    stage: release
    script:
        - echo "docker pull $CONTAINER_TEST_IMAGE"
        - echo "docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE"
        - echo "docker push $CONTAINER_RELEASE_IMAGE"
    only:
        - master

deploy:
    stage: deploy
    script:
        - echo "./deploy.sh"
    only:
        - master

